export enum OrderStatus {
    PENDING = 'PENDING',
    PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
    PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
    PROCESSING = 'PROCESSING',
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED',
    REFUNDED = 'REFUNDED'
}